;
; ---------- [ SCAN CODES ] ----------
;

; Acts as an array of key codes, while each index in the array is a scan code, which gives you its key code.
; keyArr[scanCode] == keyCode

	db 0, KBD_KEY_F9, 0, KBD_KEY_F5, KBD_KEY_F3, KBD_KEY_F1, KBD_KEY_F2, KBD_KEY_F12, 0, KBD_KEY_F10, 
	db KBD_KEY_F8, KBD_KEY_F6, KBD_KEY_F4, KBD_KEY_TAB, KBD_KEY_GRAVE, 0, 0, KBD_KEY_LEFT_ALT, KBD_KEY_LEFT_SHIFT, 0, 
	db KBD_KEY_LEFT_CTRL, KBD_KEY_Q, KBD_KEY_1, 0, 0, 0, KBD_KEY_Z, KBD_KEY_S, KBD_KEY_A, KBD_KEY_W, 
	db KBD_KEY_2, 0, 0, KBD_KEY_C, KBD_KEY_X, KBD_KEY_D, KBD_KEY_E, KBD_KEY_4, KBD_KEY_3, 0, 
	db 0, KBD_KEY_SPACE, KBD_KEY_V, KBD_KEY_F, KBD_KEY_T, KBD_KEY_R, KBD_KEY_5, 0, 0, KBD_KEY_N, 
	db KBD_KEY_B, KBD_KEY_H, KBD_KEY_G, KBD_KEY_Y, KBD_KEY_6, 0, 0, 0, KBD_KEY_M, KBD_KEY_J, 
	db KBD_KEY_U, KBD_KEY_7, KBD_KEY_8, 0, 0, KBD_KEY_COMMA, KBD_KEY_K, KBD_KEY_I, KBD_KEY_O, KBD_KEY_0, 
	db KBD_KEY_9, 0, 0, KBD_KEY_DOT, KBD_KEY_FORWARD_SLASH, KBD_KEY_L, KBD_KEY_SEMICOLON, KBD_KEY_P, KBD_KEY_MINUS, 0, 
	db 0, 0, KBD_KEY_SINGLE_QUOTE, 0, KBD_KEY_OPEN_BRACKET, KBD_KEY_EQUAL, 0, 0, KBD_KEY_CAPSLOCK, KBD_KEY_RIGHT_SHIFT, 
	db KBD_KEY_ENTER, KBD_KEY_CLOSED_BRACKET, 0, KBD_KEY_BACK_SLASH, 0, 0, 0, 0, 0, 0, 
	db 0, 0, KBD_KEY_BACKSPACE, 0, 0, KBD_KEY_1_KP, 0, KBD_KEY_4_KP, KBD_KEY_7_KP, 0, 
	db 0, 0, KBD_KEY_0_KP, KBD_KEY_DOT_KP, KBD_KEY_2_KP, KBD_KEY_5_KP, KBD_KEY_6_KP, KBD_KEY_8_KP, KBD_KEY_ESC, KBD_KEY_NUMLOCK, 
	db KBD_KEY_F11, KBD_KEY_PLUS_KP, KBD_KEY_3_KP, KBD_KEY_MINUS_KP, KBD_KEY_ASTERISK_KP, KBD_KEY_9_KP, KBD_KEY_SCROLL_LOCK, 0, 0, 0, 
	db 0, KBD_KEY_F7, 