;
; ---------- [ %DEFINE FOR ALL KEYBOARD KEY CODES ] ----------
;

%define KBD_KEY_F9 10
%define KBD_KEY_F5 6
%define KBD_KEY_F3 4
%define KBD_KEY_F1 2
%define KBD_KEY_F2 3
%define KBD_KEY_F12 13
%define KBD_KEY_F10 11
%define KBD_KEY_F8 9
%define KBD_KEY_F6 7
%define KBD_KEY_F4 5
%define KBD_KEY_TAB 28
%define KBD_KEY_GRAVE 14
%define KBD_KEY_LEFT_ALT 68
%define KBD_KEY_LEFT_SHIFT 55
%define KBD_KEY_LEFT_CTRL 67
%define KBD_KEY_Q 29
%define KBD_KEY_1 15
%define KBD_KEY_Z 56
%define KBD_KEY_S 44
%define KBD_KEY_A 43
%define KBD_KEY_W 30
%define KBD_KEY_2 16
%define KBD_KEY_C 58
%define KBD_KEY_X 57
%define KBD_KEY_D 45
%define KBD_KEY_E 31
%define KBD_KEY_4 18
%define KBD_KEY_3 17
%define KBD_KEY_SPACE 69
%define KBD_KEY_V 59
%define KBD_KEY_F 46
%define KBD_KEY_T 33
%define KBD_KEY_R 32
%define KBD_KEY_5 19
%define KBD_KEY_N 61
%define KBD_KEY_B 60
%define KBD_KEY_H 48
%define KBD_KEY_G 47
%define KBD_KEY_Y 34
%define KBD_KEY_6 20
%define KBD_KEY_M 62
%define KBD_KEY_J 49
%define KBD_KEY_U 35
%define KBD_KEY_7 21
%define KBD_KEY_8 22
%define KBD_KEY_COMMA 63
%define KBD_KEY_K 50
%define KBD_KEY_I 36
%define KBD_KEY_O 37
%define KBD_KEY_0 24
%define KBD_KEY_9 23
%define KBD_KEY_DOT 64
%define KBD_KEY_FORWARD_SLASH 65
%define KBD_KEY_L 51
%define KBD_KEY_SEMICOLON 52
%define KBD_KEY_P 38
%define KBD_KEY_MINUS 25
%define KBD_KEY_SINGLE_QUOTE 53
%define KBD_KEY_OPEN_BRACKET 39
%define KBD_KEY_EQUAL 26
%define KBD_KEY_CAPSLOCK 42
%define KBD_KEY_RIGHT_SHIFT 66
%define KBD_KEY_ENTER 54
%define KBD_KEY_CLOSED_BRACKET 40
%define KBD_KEY_BACK_SLASH 41
%define KBD_KEY_BACKSPACE 27
%define KBD_KEY_1_KP 80
%define KBD_KEY_4_KP 77
%define KBD_KEY_7_KP 73
%define KBD_KEY_0_KP 83
%define KBD_KEY_DOT_KP 84
%define KBD_KEY_2_KP 81
%define KBD_KEY_5_KP 78
%define KBD_KEY_6_KP 79
%define KBD_KEY_8_KP 74
%define KBD_KEY_ESC 1
%define KBD_KEY_NUMLOCK 70
%define KBD_KEY_F11 12
%define KBD_KEY_PLUS_KP 76
%define KBD_KEY_3_KP 82
%define KBD_KEY_MINUS_KP 72
%define KBD_KEY_ASTERISK_KP 71
%define KBD_KEY_9_KP 75
%define KBD_KEY_F7 8
