;
; ---------- [ %DEFINE FOR ALL KEYBOARD KEY CODES ] ----------
;

%define KBD_KEY_PRINT_SCREEN 14
%define KBD_KEY_PAUSE_BREAK 16
%define KBD_KEY_LEFT_WIN 71
%define KBD_KEY_RIGHT_ALT 74
%define KBD_KEY_RIGHT_WIN 75
%define KBD_KEY_MENUS 76
%define KBD_KEY_RIGHT_CTRL 77
%define KBD_KEY_INSERT 78
%define KBD_KEY_HOME 79
%define KBD_KEY_PAGE_UP 80
%define KBD_KEY_FORWARD_SLASH_KP 82
%define KBD_KEY_F9 10
%define KBD_KEY_F5 6
%define KBD_KEY_F3 4
%define KBD_KEY_F1 2
%define KBD_KEY_F2 3
%define KBD_KEY_F12 13
%define KBD_KEY_F10 11
%define KBD_KEY_F8 9
%define KBD_KEY_F6 7
%define KBD_KEY_F4 5
%define KBD_KEY_TAB 31
%define KBD_KEY_GRAVE 17
%define KBD_KEY_LEFT_ALT 72
%define KBD_KEY_LEFT_SHIFT 58
%define KBD_KEY_LEFT_CTRL 70
%define KBD_KEY_Q 32
%define KBD_KEY_1 18
%define KBD_KEY_Z 59
%define KBD_KEY_S 47
%define KBD_KEY_A 46
%define KBD_KEY_W 33
%define KBD_KEY_2 19
%define KBD_KEY_C 61
%define KBD_KEY_X 60
%define KBD_KEY_D 48
%define KBD_KEY_E 34
%define KBD_KEY_4 21
%define KBD_KEY_3 20
%define KBD_KEY_SPACE 73
%define KBD_KEY_V 62
%define KBD_KEY_F 49
%define KBD_KEY_T 36
%define KBD_KEY_R 35
%define KBD_KEY_5 22
%define KBD_KEY_N 64
%define KBD_KEY_B 63
%define KBD_KEY_H 51
%define KBD_KEY_G 50
%define KBD_KEY_Y 37
%define KBD_KEY_6 23
%define KBD_KEY_M 65
%define KBD_KEY_J 52
%define KBD_KEY_U 38
%define KBD_KEY_7 24
%define KBD_KEY_8 25
%define KBD_KEY_COMMA 66
%define KBD_KEY_K 53
%define KBD_KEY_I 39
%define KBD_KEY_O 40
%define KBD_KEY_0 27
%define KBD_KEY_9 26
%define KBD_KEY_DOT 67
%define KBD_KEY_FORWARD_SLASH 68
%define KBD_KEY_L 54
%define KBD_KEY_SEMICOLON 55
%define KBD_KEY_P 41
%define KBD_KEY_MINUS 28
%define KBD_KEY_SINGLE_QUOTE 56
%define KBD_KEY_OPEN_BRACKET 42
%define KBD_KEY_EQUAL 29
%define KBD_KEY_CAPSLOCK 45
%define KBD_KEY_RIGHT_SHIFT 69
%define KBD_KEY_ENTER 57
%define KBD_KEY_CLOSED_BRACKET 43
%define KBD_KEY_BACK_SLASH 44
%define KBD_KEY_BACKSPACE 30
%define KBD_KEY_1_KP 92
%define KBD_KEY_4_KP 89
%define KBD_KEY_7_KP 85
%define KBD_KEY_0_KP 95
%define KBD_KEY_DOT_KP 96
%define KBD_KEY_2_KP 93
%define KBD_KEY_5_KP 90
%define KBD_KEY_6_KP 91
%define KBD_KEY_8_KP 86
%define KBD_KEY_ESC 1
%define KBD_KEY_NUMLOCK 81
%define KBD_KEY_F11 12
%define KBD_KEY_PLUS_KP 88
%define KBD_KEY_3_KP 94
%define KBD_KEY_MINUS_KP 84
%define KBD_KEY_ASTERISK_KP 83
%define KBD_KEY_9_KP 87
%define KBD_KEY_SCROLL_LOCK 15
%define KBD_KEY_F7 8
